CREATE DATABASE armazenamento;
USE armazenamento;


CREATE TABLE produtos (
produtosID INT PRIMARY KEY,
COD_PROD INT NOT NULL,
VALOR_UNIT FLOAT NOT NULL,
QUANTIDADE INT NOT NULL,
DESCONTO INT
);

SELECT * FROM produtos
